global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'prometheus/*.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metric_relabel_configs:
      - regex: 'instance|pod|id|uuid'
        action: labeldrop
