apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mallos-api
spec:
  host: mallos-api
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
        idleTimeout: 30s
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mallos-api
spec:
  hosts:
    - mallos-api
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: mallos-api
            port:
              number: 3001
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: gateway-error,connect-failure,refused-stream
      timeout: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: mallos-api-rate-limit
spec:
  workloadSelector:
    labels:
      app: mallos-api
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: http_local_rate_limiter
            token_bucket:
              max_tokens: 100
              tokens_per_fill: 100
              fill_interval: 1s
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mallos-api-telemetry
spec:
  selector:
    matchLabels:
      app: mallos-api
  metrics:
    overrides:
      - match:
          metric: REQUEST_COUNT
        enabled: true
  tracing:
    providers:
      - name: "zipkin"
